### ISSUE TITLE
[Request] add Persian language

### ISSUE THREAD

**Issue by kookma** [flancast90/Speech-To-Text-in-TW5#4]
Please add Persian language

**Comment by BurningTreeC** [comment]
Hi @kookma , I've now added the persian language. Please tell us how it goes :)

**Comment by kookma** [comment]
Thank you Simon!
Sure I will share my experiences here!

**Comment by BurningTreeC** [comment]
@kookma, I've added the possibility to add user-defined keywords in addition to `Ok` and `Wiki` so that you can define for example `باشه ویکی` as your additional keywords

you would only need to create the tiddler `$:/config/speech-to-text/keywords` , add the fields `ok-keywords` and `wiki-keywords` and populate those fields with a LIST of keywords you would like to have instead of `Ok` and instead of `Wiki`

**Comment by kookma** [comment]
@BurningTreeC  thank you it works like a charm.
I will add `خب ویکی` to see how it works!

Thank you for all your efforts!

**Comment by BurningTreeC** [comment]
That's great @kookma

**Comment by BurningTreeC** [comment]
I'll close this issue for now, if you encounter problems @kookma , please open a new issue

**Comment by kookma** [comment]
Thank you @BurningTreeC . I could add some Persian words for ok wiki and it works fine!

**Comment by BurningTreeC** [comment]
Glad you understood how the mechanism works @kookma !
