### ISSUE TITLE
We should overthink how we recognize commands

### ISSUE THREAD

**Issue by BurningTreeC** [flancast90/Speech-To-Text-in-TW5#6]
There's a problem:

- A transcript can finish with `Ok Wiki` and the next transcript can start with the actual command
- We should overthink how we handle the command-recognition
- We should concatenate all transcripts together and then check for the `Ok Wiki` and the `following command`
- Having found such a command-chain, we remove it from the full transcript
- Then we process the command

**Comment by flancast90** [comment]
Ok. Sounds good. I'll add a JavaScript event to check the transcript for "Ok wiki", and then split between the open and close "Ok wiki" words. From there, the command can process as normal.

A matter of personal opinion, the "Ok wiki" end command doesn't seem to feel right. What if we started with "Ok wiki", and then ended the command with "That's all, wiki", or "that's it, wiki"?

**Comment by BurningTreeC** [comment]
>Ok. Sounds good. I'll add a JavaScript event to check the transcript for "Ok wiki", and then split between the open and close "Ok wiki" words. From there, the command can process as normal.

That's not what I meant @flancast90

**Comment by flancast90** [comment]
I think I understand what you’re saying now. Because of the continuous
recognition (which appends the transcripts together), there is some issue
with the command recognition.

Is that what you meant?

**Comment by BurningTreeC** [comment]
Yes that's what I meant @flancast90

**Comment by flancast90** [comment]
So the method we should use to fix it is, when the transcription has ended, grab the content that will be going to the tiddler, and replace all the content between Ok Wiki and the following command. It occurs to me that an "end command" phrase would make this much simpler, especially with the soon-to-come custom-commands, so that we could just search for "ok wiki", and replace from there to the "end command word (maybe That's all wiki?)", leaving us with just the transcript

**Comment by flancast90** [comment]
Sorry for my late response, I was on hold for a company trying to report an XSS vulnerability I found in their site.

**Comment by flancast90** [comment]
BTC, I've started the code on my end. I'll change it tomorrow. I have to go to work now.

Looking back at the command code you added, I was a bit confused about some things.
1) Why the commenting out of my transcript.toLowerCase()? This line reduced the need for the 100+ if/else statements you added. Instead of checking for ``Ok Vicchi, ok vicchi, ... etc.``, a simple call to check for just ``ok vicchi, ok wiki``, etc. would do the same thing "since the sentences it was checking had NO UPPERCASE LETTERS." I believe changing the code and un-commenting my transcript.toLowerCase() could reduce the number of if/else statements to 50% what it is now.

**Comment by BurningTreeC** [comment]
@flancast90 what I had in mind was refactoring the whole thing like I've done now

**Comment by flancast90** [comment]
Wow! Much better! I can imagine their is a nice increase in speed during runtime, too! What you did with the array for the similar words was exactly what I was thinking to do!

I might start a separate repo to investigate how we can programmatically evaluate sounds without that sort of method. I was thinking some sort of dictionary defining similar sounds for each letter, which, when spliced together can form quite a few words sounding similar that may be generated by the program.

**Comment by BurningTreeC** [comment]
>I might start a separate repo to investigate how we can programmatically evaluate sounds without that sort of method. I was thinking some sort of dictionary defining similar sounds for each letter, which, when spliced together can form quite a few words sounding similar that may be generated by the program.

That's an interesting idea @flancast90 :)

**Comment by BurningTreeC** [comment]
What do you think @flancast90 , should we close this issue now?

**Comment by flancast90** [comment]
Yep. You can do the honors!
